<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <script>
        function requestData(url) {
            return new Promise((resolve, reject) => {
                setTimeout(() => {
                    // resolve(url)
                    // 如果请求错误 有异常 ====> 可以通过Catch 捕获 并且继续执行代码
                    reject("error")
                }, 2000);
            })
        }
        async function getData() {
            // 第一次执行
            const res1 =  await requestData("wwww.baidu.com")
            console.log("res1: ", res1);
            // 等待 requestDatad第一次请求结束后并且 有结果后再发送第二次请求 
            const res2 =  await requestData(res1 + " wwww.weibo.com")
            console.log("res2: ", res2);

            // 也可以通过  try catch来进行捕获异常
            // try {
            //     // 第一次执行
            //     const res1 = await requestData("wwww.baidu.com")
            //     console.log("res1: ", res1);
            //     // 等待 requestDatad第一次请求结束后并且 有结果后再发送第二次请求 
            //     const res2 = await requestData(res1 + " wwww.weibo.com")
            //     console.log("res2: ", res2);
            // } catch (error) {
            //     console.log(error);
            // }
        }
        getData().catch(error => {
            console.log(error);
        })
    </script>
</body>

</html>